dist: xenial

language: r

r:
  - devel
  - release

sudo: false

cache: packages

r_check_args: --as-cran

addons:
  apt:
    packages:
      - ghostscript
      - r-cran-ggplot2
      - r-cran-brglm
      - r-cran-dynlm
      - r-cran-fgarch
      - r-cran-gee
      - r-cran-gmm
      - r-cran-knitr
      - r-cran-rmarkdown
      - r-cran-pscl
      - r-cran-rms
      - r-cran-broom
      - r-cran-sandwich
      - r-cran-testthat
      - r-cran-nlme

r_packages:
  - covr

notifications:
  email:
    recipients:
      - philip.leifeld@essex.ac.uk
      - claudia.zucca@glasgow.ac.uk
    on_success: change
    on_failure: change

after_success:
- Rscript -e 'library(covr); codecov()'
