dist: bionic

language: r

r:
  - devel
  - release

sudo: false

cache: packages

r_check_args: --as-cran

addons:
  apt:
    packages:
      - ghostscript

r_packages:
  - covr
  - ggplot2
  - AER
  - alpaca
  - betareg
  - bife
  - biglm
  - brglm
  - brms
  - btergm
  - censReg
  - dynlm
  - eha
  - erer
  - ergm
  - feisr
  - fGarch
  - forecast
  - gamlss
  - gamlss.inf
  - gee
  - geepack
  - glmmADMB
  - glmmTMB
  - gmm
  - gnm
  - h2o
  - latentnet
  - lfe
  - lme4
  - lqmm
  - MASS
  - metaSEM
  - mfx
  - mgcv
  - mhurdle
  - miceadds
  - mlogit
  - mnlogit
  - MuMIn
  - nlme
  - nnet
  - oglmx
  - ordinal
  - panelAR
  - pglm
  - pgmm
  - plm
  - pscl
  - quantreg
  - relevent
  - rms
  - robust
  - robustbase
  - RSiena
  - sampleSelection
  - simex
  - sna
  - spdep
  - speedglm
  - survey
  - survival
  - systemfit
  - tergm
  - VGAM

notifications:
  email:
    recipients:
      - philip.leifeld@essex.ac.uk
      - claudia.zucca@glasgow.ac.uk
    on_success: change
    on_failure: change

after_success:
   - Rscript -e 'library(covr); codecov()'
