dist: bionic

language: r

r:
  - devel
  - release

sudo: false

cache: packages

r_check_args: --as-cran

addons:
  apt:
    packages:
      - ghostscript

r_packages:
  - lmtest
  - sandwich
  - nlme
  - knitr
  - rmarkdown
  - httr
  - ggplot2
  - testthat
  - covr

notifications:
  email:
    recipients:
      - philip.leifeld@essex.ac.uk
      - claudia.zucca@glasgow.ac.uk
    on_success: change
    on_failure: change

after_success:
- Rscript -e 'library(covr); codecov()'
