dist: bionic

language: r

r:
  - devel
  - release

sudo: false

cache: packages

r_check_args: --as-cran

addons:
  apt:
    packages:
      - ghostscript
      - r-cran-ggplot2
      - r-cran-knitr
      - r-cran-rmarkdown
      - r-cran-sandwich
      - r-cran-testthat
      - r-cran-nlme
      - r-cran-lmtest

r_packages:
  - httr
  - covr

notifications:
  email:
    recipients:
      - philip.leifeld@essex.ac.uk
      - claudia.zucca@glasgow.ac.uk
    on_success: change
    on_failure: change

after_success:
- Rscript -e 'library(covr); codecov()'
