on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: testthat

jobs:
  testthat:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - name: Query dependencies
        run: |
          install.packages("devtools")
          saveRDS(devtools::dev_package_deps(dependencies = c("Depends", "Imports", "LinkingTo", "Suggests")), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.0-2-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-4.0-2-

      - name: Install dependencies
        run: |
          devtools::install_deps(dependencies = TRUE)
          install.packages(c("forecast", "Bergm", "bife", "brms", "ordinal", "dynlm", "alpaca", "feisr", "lfe", "fixest", "gamlss.inf", "miceadds", "lme4", "glmmTMB", "AER", "speedglm", "truncreg", "eha", "metaSEM", "biglm", "mlogit"))
        shell: Rscript {0}

      - name: Unit testing
        run: withr::with_envvar(c("NOT_CRAN" = "true"), devtools::test())
        shell: Rscript {0}
